version: '3.3'

services:
  consul:
    image: consul:latest
    container_name: "consul"
    hostname: "consul"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
    networks:
      - "micro"
    ports:
      - "8301:8301"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetInterfaceIP \"eth0\" }}'"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "jaeger"
    hostname: "jaeger"
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
    networks:
      - "micro"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
networks:
  micro:
